export const SET_SELECTION_RANGE = 'SET_SELECTION_RANGE';
export const SET_TEXT = 'SET_TEXT';
export const REPLACE_WORD = 'REPLACE_WORD';
export const APPLY_DECORS = 'APPLY_DECORS';

export const GET_SYNONIM_START = 'GET_SYNONIM_START';
export const GET_SYNONIM_SUCCESS = 'GET_SYNONIM_SUCCESS';
export const RESET_SYNONIM_WORD = 'RESET_SYNONIM_WORD';